[BE] 회원가입 예외 처리 기능 | AA-76-회원가입-예외-처리 => BE
yumyeonghan/Another_Art pull request #14
Opened 2022-08-18 03:04 UTC by eunchannam

1. 로그인 아이디 중복 체크
2. 닉네임 중복 체크
3. 전화번호 중복 체크

* 하나의 UserDuplicationException으로 정의함

2022-08-18 03:55 UTC, sjiwon requested changes
(#14) PR에 대한 코드 리뷰 남겼습니다

2022-08-18 03:55 UTC, sjiwon commented on src/main/java/com/imagine/another_arts/web/user/UserController.java
> +    }
중복체크 [로그인 아이디, 닉네임, 전화번호]를 PathVariable의 type으로 분리하지 않고 각각의 중복 체크 컨트롤러를 따로 설계하는거는 어떤가요??

그리고 중복 체크 로직 자체를 컨트롤러에서 수행하지 않고 Service Layer로 체크받을 값을 넘겨주어서 Service Layer에서 값에 대한 검증 결과를 받아오는것이 각 Layer별로 목적이 명확해 지는거 같아요

2022-08-18 03:55 UTC, sjiwon commented on src/main/java/com/imagine/another_arts/web/user/UserExceptionHandler.java
> +    }
NOT_ACCEPTABLE = 406 예외는 Client가 Http Request Message를 보낼 때 Accept Header에 원하는 결과 양식들을 지정했는데 Server에서 지정한 양식대로 응답을 하지 못해서 발생하는 예외로 알고 있습니다.

위의 중복 체크 로직 자체는 Response Type에 대한 예외가 아니라 DB상에 Unique값들에 대한 중복을 체크함에 따라 발생하는 예외이기 때문에 406보다는 409(Conflict)예외가 더 적절하다고 생각이 드네요
> https://deveric.tistory.com/62
> https://chihunmanse.github.io/http2/
> https://developer.mozilla.org/ko/docs/Web/HTTP/Content_negotiation

2022-08-18 05:04 UTC, eunchannam commented on src/main/java/com/imagine/another_arts/web/user/UserController.java
> +    }
그부분 고민했었는데 분리할게용

2022-08-26 11:22 UTC, eunchannam commented on src/main/java/com/imagine/another_arts/web/user/UserExceptionHandler.java
> +    }
수정 했습니다~

2022-08-26 11:22 UTC, merged